paths:
  video_folder: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/HumanEva_walking/
  output_dir: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/test_videos_results_from_yaml
  csv_file: C:\Users\BhavyaSehgal\Downloads\bhavya_phd\Tested_dataset\humaneva_sorted_by_subject.csv

video:
  extensions:
    - .mp4
    - .avi
    - .mov
    - .mkv

models:
  det_config: /storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
  det_checkpoint: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
  pose_config: /storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/mmpose/projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb704-270e_cocktail14-256x192.py
  pose_checkpoint: /storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/rtmw-x_simcc-cocktail14_pt-ucoco_270e-256x192-13a2546d_20231208.pth

processing:
  device: cuda:0
  nms_threshold: 0.5
  detection_threshold: 0.3
  kpt_threshold: 0.3

noise:
  apply_poisson_noise: true
  apply_gaussian_noise: true
  apply_motion_blur: true
  apply_brightness_reduction: true
  brightness_factor: 30
  poisson_scale: 1.0
  gaussian_std: 2.0
  motion_blur_kernel_size: 5
  target_resolution: null  # or [640, 480]


filter:
  name: "gaussian"  # e.g. "butterworth", "kalman", "savitzky", etc.
  params:
    sigma: 0.5      # filter-specific parameter

  outlier_removal:
    enable: True
    method: "iqr"   # or "zscore"
    params:
      iqr_multiplier: 1.5   # or z_threshold for zscore

  enable_interpolation: true
  interpolation_kind: "linear"

  enable_filter_plots: true

  joints_to_filter:
    - LEFT_ANKLE
    - RIGHT_ANKLE
    - LEFT_KNEE
    - RIGHT_KNEE
    - LEFT_HIP
    - RIGHT_HIP



analysis:
  # PCK thresholds for assessment (change or add more if needed)
  pck_thresholds: [0.01, 0.02, 0.05, 0.1]
  excel_output_filename: combined_assessment_results.xlsx

sync_data:
  data:
    S1:
      Walking 1: [667, 667, 667]
      Jog 1: [49, 50, 51]
    S2:
      Walking 1: [547, 547, 546]
      Jog 1: [493, 491, 502]
    S3:
      Walking 1: [524, 524, 524]
      Jog 1: [464, 462, 462]
