orchestrator:
  log_dir: "./logs"
  default_device: "cuda:0"

pipelines:
    # 4th order Butterworth – HumanEva (1–10 Hz)
  - name: filter_butterworth_4th_1hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_1hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_2hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_2hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_3hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_3hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_4hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_4hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_5hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_5hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_6hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_6hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_7hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_7hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_8hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_8hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_9hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_9hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_4th_10hz_humaneva
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_10hz_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

    # 4th order Butterworth – HumanSC3D (1–10 Hz)
  - name: filter_butterworth_4th_1hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_1hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_2hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_2hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_3hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_3hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_4hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_4hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_5hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_6hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_6hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_7hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_7hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_8hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_8hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_9hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_9hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  - name: filter_butterworth_4th_10hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_4th_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
