orchestrator:
  log_dir: "./logs"
  default_device: "cuda:0"

pipelines:
    - name: filter_butterworth_2nd_1hz
      steps:
        - command: evaluation
          config_file: "dataset_files/HumanEva/humaneva_config.yaml"

    - name: filter_butterworth_2nd_6hz
      steps:
        - command: evaluation
          config_file: "dataset_files/HumanEva/humaneva_config.yaml"

    - name: filter_butterworth_4th_6hz
      steps:
        - command: evaluation
          config_file: "dataset_files/HumanEva/humaneva_config.yaml"

    - name: filter_butterworth_2nd_15hz
      steps:
        - command: evaluation
          config_file: "dataset_files/HumanEva/humaneva_config.yaml"
