orchestrator:
  log_dir: "./logs"
  default_device: "cuda:0"

pipelines:

#   - name: run_pose_estimation
#     steps:
#       - command: detect
#         config_file: "config_yamls/pipeline_config.yaml"

  # - name: simulate_noise
  #   steps:
  #     - command: noise
  #       config_file: "config_yamls/pipeline_config.yaml"

  - name: run_pose_estimation_and_filter
    steps:
      - command: detect
        config_file: "config_yamls/pipeline_config.yaml"
      - command: filter
        config_file: "config_yamls/detect_and_filter.yaml"

  # - name: run_filter_and_assess
  #   steps:
  #     - command: filter
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"


  # - name: evaluate_pose_accuracy
  #   steps:
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"
