orchestrator:
  log_dir: "./logs"
  default_device: "cuda:0"

pipelines:
  # Butterworth Filter - Example configuration
  # - name: filter_butterworth_example
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_butterworth_18th_5hz.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # Butterworth Filters for HumanSC3D (orders 1,5,10,15,18, cutoff 5,10,15,18 Hz)

  # 1st order
  - name: filter_butterworth_1st_5hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_1st_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_1st_10hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_1st_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_1st_15hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_1st_15hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_1st_18hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_1st_18hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"


  # 5th order
  - name: filter_butterworth_5th_5hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_5th_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_5th_10hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_5th_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_5th_15hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_5th_15hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_5th_18hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_5th_18hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  # 7th order
  - name: filter_butterworth_7th_5hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_7th_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_7th_10hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_7th_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_7th_15hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_7th_15hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_7th_18hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_7th_18hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  # 10th order
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_10th_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_10th_10hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_10th_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_10th_15hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_10th_15hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_10th_18hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_10th_18hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  # 15th order
  - name: filter_butterworth_15th_5hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_15th_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_15th_10hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_15th_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_15th_15hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_15th_15hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_15th_18hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_15th_18hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  # 18th order
  - name: filter_butterworth_18th_5hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_5hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_18th_10hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_10hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_18th_15hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_15hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"
  - name: filter_butterworth_18th_18hz_humansc3d
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_18hz.yaml"
      - command: evaluation
        config_file: "/storage/Projects/Gaitly/bsehgal/Lower-Body-Pose-Estimation-for-Human-Motion-Analysis/dataset_files/HumanSC3D/humansc3d_config_nojoints.yaml"

  

  # Extended Kalman Filter - Example configuration
  # - name: filter_ekf_example
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_extended_kalman_walking_smooth_high_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # Unscented Kalman Filter - Example configuration
  # - name: filter_ukf_example
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_unscented_kalman_walking_smooth_high_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # Standard Kalman Filter - Example configuration
  # - name: filter_kalman_example
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_smooth_walking_high_acc_mid.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  