orchestrator:
  log_dir: "./logs"
  default_device: "cuda:0"

pipelines:
  - name: detect_dwpose
    steps:
      - command: detect
        config_file: "config_yamls/DWPose_detector.yaml"
      - command: evaluation
        config_file: "config_yamls/DWPose_detector_movi.yaml"

  # - name: detect_RTMW
  #   steps:
  #     - command: detect
  #       config_file: "config_yamls/DWPose_detector_humaneva.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: detect_DWPose
    steps:
      - command: detect
        config_file: "config_yamls/DWPose_detector_humaneva.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: detect_RTMW
  #   steps:
  #     # - command: detect
  #     #   config_file: "config_yamls/rtmw_detector.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/MoVi/MoVi_test.yaml"


  # - name: test_noise_20
  #   steps:
  #     - command: noise
  #       config_file: "config_yamls/test_noise_20.yaml"

  # - name: test_noise_30
  #   steps:
  #     - command: noise
  #       config_file: "config_yamls/test_noise_30.yaml"


  # - name: savgol_filter_pipeline_60_3
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_savgol.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  
  # - name: savgol_filter_pipeline_15_3
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_savgol_11.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: savgol_filter_pipeline_31_2
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_savgol_11.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"


  # - name: gaussian_filter_pipeline_3
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_gaussian_3.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: gaussian_filter_pipeline_1point5
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_gaussian_1.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: gaussian_filter_pipeline_2point5
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_gaussian.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: butterworth_2nd_order_4hz_pipeline
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_butterworth_4th_8hz.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: butterworth_3th_order_6hz_pipeline
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_butterworth_3nd_5hz.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: butterworth_5th_order_5hz_pipeline
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_butterworth_2nd_1hz.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: gvcspl_filter_pipeline
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_gvcspl.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: fdf_pipeline
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_fdf.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: kalman_filter
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter_with_kalman.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

