orchestrator:
  log_dir: "./logs"
  default_device: "cuda:0"

pipelines:

  # Sample butterworth filter configuration (reference only)
  # - name: filter_butterworth_10th_10hz
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_butterworth_10th_10hz.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # Order 18 butterworth filters (1-7 Hz cutoff frequencies)
  - name: filter_butterworth_18th_1hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_1hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_2hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_2hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_3hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_3hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_4hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_4hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_5hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_5hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_6hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_6hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_7hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_7hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # Order 18 butterworth filters (10-15 Hz cutoff frequencies)
  - name: filter_butterworth_18th_10hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_10hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_11hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_11hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_12hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_12hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_13hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_13hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_14hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_14hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  - name: filter_butterworth_18th_15hz
    steps:
      - command: filter
        config_file: "config_yamls/filter/filter_butterworth_18th_15hz.yaml"
      - command: evaluation
        config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # EKF (Extended Kalman Filter) configurations
  # - name: filter_ekf_walking_smooth_high_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_extended_kalman_walking_smooth_high_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_ekf_fast_gait_medium_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_extended_kalman_fast_gait_medium_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_ekf_smooth_motion_low_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_extended_kalman_smooth_motion_low_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_ekf_walking_medium_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_extended_kalman_walking_medium_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # # UKF (Unscented Kalman Filter) configurations
  # - name: filter_ukf_walking_smooth_high_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_unscented_kalman_walking_smooth_high_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_ukf_fast_gait_medium_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_unscented_kalman_fast_gait_medium_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_ukf_smooth_motion_low_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_unscented_kalman_smooth_motion_low_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_ukf_walking_medium_acc
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_unscented_kalman_walking_medium_acc.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # # Standard Kalman Filter configurations with expanded parameter ranges
  # - name: filter_kalman_smooth_walking_high_acc_low
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_smooth_walking_high_acc_low.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_smooth_walking_high_acc_mid
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_smooth_walking_high_acc_mid.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_smooth_walking_high_acc_high
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_smooth_walking_high_acc_high.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_normal_gait_medium_acc_low
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_normal_gait_medium_acc_low.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_normal_gait_medium_acc_mid
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_normal_gait_medium_acc_mid.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_normal_gait_medium_acc_high
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_normal_gait_medium_acc_high.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_fast_gait_low_acc_low
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_fast_gait_low_acc_low.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_fast_gait_low_acc_mid
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_fast_gait_low_acc_mid.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"

  # - name: filter_kalman_fast_gait_low_acc_high
  #   steps:
  #     - command: filter
  #       config_file: "config_yamls/filter/filter_kalman_fast_gait_low_acc_high.yaml"
  #     - command: evaluation
  #       config_file: "dataset_files/HumanEva/humaneva_config.yaml"