from ..deeplabcut.frame_processor_deeplabcut import FrameProcessorDLC
from .detector_deeplabcut import DeepLabCutDetector
from .deeplabcut_visualization import DeepLabCutVisualizer
from skeleton_config import bodyparts2connect
