bodyparts2connect = [
    ("right_ankle", "right_knee"),
    ("right_knee", "right_hip"),
    ("left_ankle", "left_knee"),
    ("left_hip", "left_knee"),
    ("left_hip", "right_hip"),
    ("right_shoulder", "right_hip"),
    ("left_shoulder", "left_hip"),
    ("left_shoulder", "right_shoulder"),
    ("left_shoulder", "left_elbow"),
    ("right_shoulder", "right_elbow"),
    ("left_elbow", "left_wrist"),
    ("right_elbow", "right_wrist"),
    ("right_eye", "left_ear"),
    ("left_eye", "right_eye"),
    ("left_eye", "left_ear"),
    ("right_eye", "right_ear"),
    ("left_ear", "left_shoulder"),
    ("right_ear", "right_shoulder"),
    ("left_shoulder", "left_elbow"),
    ("right_shoulder", "right_elbow"),
]
