# CLAHE Enhancement Pipeline Configuration for HumanEva Dataset - Aggressive Settings
# This configuration uses aggressive CLAHE parameters for strong enhancement

# Dataset and path configuration
paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

# Enhancement configuration
enhancement:
  # Type of enhancement to apply (required)
  type: clahe  # Options: clahe, histogram_eq, gaussian_blur, brightness_adjustment
  
  # Comparison images setting
  create_comparison_images: true  # Generate before/after comparison images for first frames
  
  # CLAHE specific settings - AGGRESSIVE (strong enhancement)
  clahe:
    clip_limit: 4.0  # Higher clip limit for stronger contrast enhancement
    tile_grid_size: [16, 16]  # Larger grid for more localized adaptation
    color_space: LAB  # Options: LAB, RGB, HSV
  
  # Processing settings
  processing:
    batch_size: 8  # Slightly smaller batch for more intensive processing
    dataset_structure: true  # Whether videos are organized in subject/action structure
    generate_report: true  # Generate enhancement comparison report

# Output settings
output:
  prefix: clahe_aggressive_  # Prefix for enhanced video files
  format: mp4  # Output video format
  quality: high  # Options: low, medium, high
  preserve_structure: true  # Maintain directory structure in output

# Notes:
# - Aggressive settings for maximum contrast enhancement
# - Higher clip_limit (4.0) allows for stronger local contrast
# - Larger tile grid (16x16) provides very localized adaptation
# - Good for dark or low-contrast videos
# - May introduce artifacts in well-lit scenes
