# CLAHE Enhancement Pipeline Configuration for HumanEva Dataset - Ultra Fine Grid
# This configuration uses ultra-fine grid for maximum local detail enhancement

# Dataset and path configuration
paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

# Enhancement configuration
enhancement:
  # Type of enhancement to apply (required)
  type: clahe  # Options: clahe, histogram_eq, gaussian_blur, brightness_adjustment
  
  # Comparison images setting
  create_comparison_images: true  # Generate before/after comparison images for first frames
  
  # CLAHE specific settings - ULTRA FINE GRID for maximum detail
  clahe:
    clip_limit: 2.8  # Moderate-high clip limit for detailed enhancement
    tile_grid_size: [20, 20]  # Ultra fine 20x20 grid for maximum local detail
    color_space: LAB  # LAB color space for perceptually uniform enhancement
  
  # Processing settings
  processing:
    batch_size: 6  # Smaller batch for intensive ultra-fine processing
    dataset_structure: true  # Whether videos are organized in subject/action structure
    generate_report: true  # Generate enhancement comparison report

# Output settings
output:
  prefix: clahe_ultra_fine_  # Prefix for enhanced video files
  format: mp4  # Output video format
  quality: high  # Options: low, medium, high
  preserve_structure: true  # Maintain directory structure in output

# Notes:
# - Uses ultra-fine 20x20 grid for maximum local detail enhancement
# - Excellent for preserving and enhancing fine details like joint boundaries
# - Higher computational cost due to fine grid processing
# - May be particularly effective for pose estimation with small joint features
# - Good for high-resolution videos where fine detail matters
# - Can reveal subtle contrast differences in clothing, skin, and background
