# Enhancement Pipeline Configuration for HumanEva Dataset
# This configuration works with the new enhancement_pipeline.py

# Dataset and path configuration
paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

# Enhancement configuration
enhancement:
  # Type of enhancement to apply (required)
  type: clahe  # Options: clahe, histogram_eq, gaussian_blur, brightness_adjustment
  
  # Comparison images setting
  create_comparison_images: true  # Generate before/after comparison images for first frames
  
  # CLAHE specific settings (required when type is clahe)
  clahe:
    clip_limit: 2.0  # Slightly lower clip limit for HumanEva
    tile_grid_size: [8, 8]
    color_space: LAB  # Options: LAB, RGB, HSV
  
  # Brightness adjustment settings (required when type is brightness_adjustment)
  # brightness:
  #   factor: 1.1  # Brightness multiplication factor
  
  # Gaussian blur settings (required when type is gaussian_blur)
  # blur:
  #   kernel_size: [3, 3]  # Blur kernel size
  #   sigma_x: 0
  #   sigma_y: 0
  
  # Processing settings
  processing:
    batch_size: 10  # Number of videos to process at once
    dataset_structure: true  # Whether videos are organized in subject/action structure
    generate_report: true  # Generate enhancement comparison report


