# Enhancement Pipeline Configuration for HumanEva Dataset
# This configuration works with the new enhancement_pipeline.py

# Dataset and path configuration
paths:
  dataset: HumanEva
  input_dir: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/dataset/HumanEva/videos
  output_dir: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/dataset/HumanEva/enhanced

# Enhancement configuration
enhancement:
  # Type of enhancement to apply (required)
  type: clahe  # Options: clahe, histogram_eq, gaussian_blur, brightness_adjustment
  
  # CLAHE specific settings (required when type is clahe)
  clahe:
    clip_limit: 2.0  # Slightly lower clip limit for HumanEva
    tile_grid_size: [8, 8]
    color_space: LAB  # Options: LAB, RGB, HSV
  
  # Brightness adjustment settings (required when type is brightness_adjustment)
  # brightness:
  #   factor: 1.1  # Brightness multiplication factor
  
  # Gaussian blur settings (required when type is gaussian_blur)
  # blur:
  #   kernel_size: [3, 3]  # Blur kernel size
  #   sigma_x: 0
  #   sigma_y: 0
  
  # Processing settings
  processing:
    batch_size: 10  # Number of videos to process at once
    dataset_structure: true  # Whether videos are organized in subject/action structure
    generate_report: true  # Generate enhancement comparison report

# Dataset structure (for structured processing)
dataset:
  name: HumanEva
  structure:
    type: subject_action  # subject/action/videos organization
    subjects: ['S1', 'S2', 'S3']
    actions: ['Walking', 'Jogging', 'ThrowCatch', 'Gestures', 'Boxing', 'Balance']
  
  # Video file settings
  video:
    extensions: ['.mp4', '.avi', '.mov']
    fps: 60
    resolution: [640, 480]

# Output settings
output:
  prefix: enhanced_  # Prefix for enhanced video files
  format: mp4  # Output video format
  quality: high  # Options: low, medium, high
  preserve_structure: true  # Maintain directory structure in output
