# Filtered CLAHE Enhancement Pipeline Configuration
# CLAHE (clip_limit: 0.5, tile_grid_size: 8x8) + Combined Filters (Bilateral + Gaussian)

# Dataset and path configuration
paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

models:
  detector: rtmw
  det_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
  det_checkpoint: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
  pose_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail14/rtmw-x_8xb320-270e_cocktail14-384x288.py
  pose_checkpoint: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/rtmw-x_simcc-cocktail14_pt-ucoco_270e-384x288-f840f204_20231122.pth

processing:
  device: cuda:0
  nms_threshold: 0.5
  detection_threshold: 0.3
  kpt_threshold: 0.3

# Enhancement configuration
enhancement:
  type: filtered_clahe
  create_comparison_images: true
  
  # Filtered CLAHE specific settings
  filtered_clahe:
    clip_limit: 0.5
    tile_grid_size: [8, 8]
    color_space: HSV
    filters: ["bilateral", "gaussian"]
    filter_params:
      bilateral:
        d: 9
        sigma_color: 75.0
        sigma_space: 75.0
      gaussian:
        kernel_size: [3, 3]
        sigma_x: 0.5
        sigma_y: 0.5
  
  processing:
    batch_size: 8
    dataset_structure: true
    generate_report: true

# Output settings
output:
  prefix: filtered_clahe_05_8x8_combined_
  format: mp4
  quality: high
  preserve_structure: true

evaluation:
  metrics:
    - name: overall_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.3
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

dataset:
  joint_enum_module: utils.joint_enum.GTJointsHumanEVa
  keypoint_format: utils.joint_enum.PredJointsDeepLabCut
  sync_data:
    data:
      S1:
        Walking 1: [667, 667, 667]
        Jog 1: [49, 50, 51]
      S2:
        Walking 1: [547, 547, 546]
        Jog 1: [493, 491, 502]
      S3:
        Walking 1: [524, 524, 524]
        Jog 1: [464, 462, 462]
