# Flexible Filtered Gamma Enhancement Pipeline Configuration
# Gamma correction with filtering BEFORE enhancement only
# This applies denoising before gamma correction

# Dataset and path configuration
paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

models:
  detector: rtmw
  det_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
  det_checkpoint: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
  pose_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail14/rtmw-x_8xb320-270e_cocktail14-384x288.py
  pose_checkpoint: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/rtmw-x_simcc-cocktail14_pt-ucoco_270e-384x288-f840f204_20231122.pth

processing:
  device: cuda:0
  nms_threshold: 0.5
  detection_threshold: 0.3
  kpt_threshold: 0.3

# Enhancement configuration with flexible filtering
enhancement:
  type: flexible_filtered_gamma
  create_comparison_images: true
  
  # Flexible Filtered Gamma specific settings
  flexible_filtered_gamma:
    gamma: 0.8
    color_space: HSV
    filter_mode: before  # Apply filters BEFORE gamma correction
    
    # Pre-enhancement filters (noise reduction before gamma correction)
    pre_filters: ["bilateral"]
    pre_filter_params:
      non_local_means:
        h: 10.0
        template_window_size: 7
        search_window_size: 21
      bilateral:
        d: 9
        sigma_color: 75.0
        sigma_space: 75.0
    
    # Post-enhancement filters (empty for 'before' mode)
    post_filters: []
    post_filter_params: {}
  
  processing:
    batch_size: 8
    dataset_structure: true
    generate_report: true

# Output settings
output:
  prefix: flexible_gamma_before_filter_
  format: mp4
  quality: high
  preserve_structure: true

evaluation:
  metrics:
    - name: overall_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

dataset:
  joint_enum_module: utils.joint_enum.GTJointsHumanEVa
  keypoint_format: utils.joint_enum.PredJointsDeepLabCut
  sync_data:
    data:
      S1:
        Walking 1: [667, 667, 667]
        Jog 1: [49, 50, 51]
      S2:
        Walking 1: [547, 547, 546]
        Jog 1: [493, 491, 502]
      S3:
        Walking 1: [524, 524, 524]
        Jog 1: [464, 462, 462]
