# Gamma Correction Enhancement Pipeline Configuration - Conservative Settings
# This configuration uses conservative gamma correction for subtle brightening

# Dataset and path configuration
paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

models:
  detector: rtmw
  det_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
  det_checkpoint: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
  pose_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail14/rtmw-x_8xb320-270e_cocktail14-384x288.py
  pose_checkpoint: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/rtmw-x_simcc-cocktail14_pt-ucoco_270e-384x288-f840f204_20231122.pth

processing:
  device: cuda:0
  nms_threshold: 0.5
  detection_threshold: 0.3
  kpt_threshold: 0.3

# Enhancement configuration
enhancement:
  # Type of enhancement to apply (required)
  type: gamma_correction  # Options: clahe, histogram_eq, gaussian_blur, brightness_adjustment, gamma_correction
  
  # Comparison images setting
  create_comparison_images: true  # Generate before/after comparison images for first frames
  
  # Gamma correction specific settings - CONSERVATIVE (subtle brightening)
  gamma:
    gamma: 0.9  # Slightly brighten (gamma < 1.0 brightens, gamma > 1.0 darkens)
    color_space: HSV
    input_dir: null
    output_dir: null
    file_extensions: [".mp4", ".avi", ".mov", ".mkv"]
  
  # Processing settings
  processing:
    batch_size: 10  # Number of videos to process at once
    dataset_structure: true  # Whether videos are organized in subject/action structure
    generate_report: true  # Generate enhancement comparison report

# Output settings
output:
  prefix: gamma_conservative_  # Prefix for enhanced video files
  format: mp4  # Output video format
  quality: high  # Options: low, medium, high
  preserve_structure: true  # Maintain directory structure in output

# Notes:
# - Conservative gamma correction (0.9) for subtle brightening
# - Applied to all BGR channels for natural color preservation
# - Good for slightly underexposed videos
# - Minimal risk of overexposure or color distortion

evaluation:
  metrics:
    - name: overall_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.3
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.35
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.4
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.3
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.35
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.4
        joints_to_evaluate:
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

dataset:
  joint_enum_module: utils.joint_enum.GTJointsHumanEVa
  keypoint_format: utils.joint_enum.PredJointsDeepLabCut
  sync_data:
    data:
      S1:
        Walking 1: [667, 667, 667]
        Jog 1: [49, 50, 51]
      S2:
        Walking 1: [547, 547, 546]
        Jog 1: [493, 491, 502]
      S3:
        Walking 1: [524, 524, 524]
        Jog 1: [464, 462, 462]
