# Example Analysis Configuration with Bin Size Settings
# This file demonstrates how to configure different bin sizes for brightness analysis

analysis:
  pck_brightness:
    # Default bin size for brightness analysis
    bin_size: 2
    
    # Alternative bin sizes for different scenarios
    bin_sizes:
      ultra_fine: 1      # For very detailed analysis
      fine: 2           # For detailed analysis  
      default: 5        # Standard analysis
      coarse: 10        # For overview analysis
      very_coarse: 20   # For rapid overview
      extreme_coarse: 50 # For very broad patterns
    
    # Score groups for different analysis scenarios
    score_groups:
      all: null  # Analyze all available scores
      extremes: [0, 100]  # Only extreme scores
      high_performance: [80, 85, 90, 95, 100]
      low_performance: [0, 5, 10, 15, 20]
      mid_range: [40, 45, 50, 55, 60]
      research_points: [50, 70, 85, 95]
    
    # Analysis scenarios with specific bin sizes
    scenarios:
      - name: "detailed_extremes"
        score_group: "extremes"
        bin_size: 1
        description: "Ultra-detailed analysis of extreme scores"
        
      # - name: "overview_all"
      #   score_group: "all" 
      #   bin_size: 20
      #   description: "Broad overview of all scores"
        
      # - name: "precision_high_performance"
      #   score_group: "high_performance"
      #   bin_size: 2
      #   description: "Precise analysis of high-performing scores"
        
      # - name: "standard_research"
      #   score_group: "research_points"
      #   bin_size: 5
      #   description: "Standard analysis for research comparison"

# Usage examples:
# 1. Use default bin size: python pck_brightness_analysis.py movi
# 2. Override bin size: python pck_brightness_analysis.py movi --bin-size 10
# 3. Fine-grained analysis: python pck_brightness_analysis.py humaneva --bin-size 1 --scores 95 100
# 4. Quick overview: python pck_brightness_analysis.py movi --bin-size 20
