# Analysis Configuration for PCK Brightness Analysis
# This file defines score groups and analysis scenarios for PCK brightness plots

analysis:
  pck_brightness:
    # Score groups for different analysis scenarios
    score_groups:
      all: null  # null means analyze all available scores
      extremes: [0, 100]  # Only analyze extreme scores (worst and best)
      high_performance: [80, 85, 90, 95, 100]  # High-performing scores
      low_performance: [0, 5, 10, 15, 20]  # Low-performing scores
      mid_range: [40, 45, 50, 55, 60]  # Mid-range scores
      custom: [70, 80, 90]  # Custom selection for comparison
      
      # Additional score groups for detailed analysis:
      deciles: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  # Every 10%
      quintiles: [0, 20, 40, 60, 80, 100]  # Every 20%
      binary: [0, 100]  # Just failure and success
      near_perfect: [90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]  # Near perfect scores
      poor_performance: [0, 5, 10, 15, 20, 25, 30]  # Detailed poor performance
      good_performance: [70, 75, 80, 85, 90, 95, 100]  # Good performance range
      research_focused: [50, 60, 70, 80, 90]  # Research comparison points
      
      # Specialized analysis groups:
      threshold_analysis: [0, 25, 50, 75, 100]  # Threshold-based analysis
      fine_grained: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100]
      coarse_grained: [0, 33, 66, 100]  # Coarse analysis
    
    # Default score group to use
    default_score_group: "extremes"
    
    # Multiple analyses to run in sequence
    multi_analysis:
      enabled: true
      scenarios:
        - name: "complete_analysis"
          score_group: "all"
          description: "Analysis of all available PCK scores"
        - name: "extremes_analysis" 
          score_group: "extremes"
          description: "Analysis of extreme PCK scores (0 and 100)"
        - name: "high_performance_analysis"
          score_group: "high_performance"
          description: "Analysis of high-performing PCK scores"
        - name: "threshold_analysis"
          score_group: "threshold_analysis"
          description: "Analysis using threshold-based score groups"
        - name: "research_analysis"
          score_group: "research_focused"
          description: "Analysis focused on research comparison points"
    
    # Visualization settings for plots
    visualization:
      create_individual_plots: true
      create_combined_plots: true
      create_comparison_plots: true
      save_format: "svg"
      
      # Plot-specific settings
      plot_settings:
        figure_size: [12, 8]
        dpi: 300
        line_width: 2
        marker_size: 6
        font_size: 12
        title_font_size: 14
        color_palette: "viridis"  # matplotlib colormap
        
    # Export settings
    export:
      csv_enabled: true
      json_enabled: true
      separate_files_per_group: true
      include_summary_statistics: true

  # Configuration for other analysis types
  statistical:
    confidence_level: 0.95
    significance_threshold: 0.05
    
  distribution:
    bin_size: 5
    normalize: true
    
  correlation:
    method: "pearson"
    min_samples: 10

# General analysis settings
general:
  output_prefix: "analysis"
  timestamp_format: "%Y%m%d_%H%M%S"
  create_summary_report: true
  verbose_logging: true
  
# Dataset-specific overrides
dataset_overrides:
  humaneva:
    default_score_group: "extremes"
    preferred_scenarios: ["extremes_analysis", "high_performance_analysis"]
    
  movi:
    default_score_group: "extremes" 
    preferred_scenarios: ["extremes_analysis", "threshold_analysis"]
