# Example Analysis Configuration with Bin Size Settings
# This file demonstrates how to configure different bin sizes for brightness analysis

analysis:
  pck_brightness:
    # Default bin size for brightness analysis
    bin_size: 2
    
    # Alternative bin sizes for different scenarios
    bin_sizes:
      ultra_fine: 1      # For very detailed analysis
      fine: 2           # For detailed analysis  
      default: 5        # Standard analysis
      coarse: 10        # For overview analysis
      very_coarse: 20   # For rapid overview
      extreme_coarse: 50 # For very broad patterns
    
    # Score groups for different analysis scenarios
    score_groups:
      all: null  # Analyze all available scores
      extremes: [0, 100]  # Only extreme scores
      high_performance: [80, 85, 90, 95, 100]
      low_performance: [0, 5, 10, 15, 20]
      mid_range: [40, 45, 50, 55, 60]
      research_points: [50, 70, 85, 95]
    
    # Analysis scenarios with specific bin sizes
    scenarios:
      - name: "detailed_extremes"
        score_group: "extremes"
        bin_size: 1
        description: "Ultra-detailed analysis of extreme scores"
        
      # - name: "overview_all"
      #   score_group: "all" 
      #   bin_size: 20
      #   description: "Broad overview of all scores"
        
      # - name: "precision_high_performance"
      #   score_group: "high_performance"
      #   bin_size: 2
      #   description: "Precise analysis of high-performing scores"
        
      # - name: "standard_research"
      #   score_group: "research_points"
      #   bin_size: 5
      #   description: "Standard analysis for research comparison"

  # Multi-dataset box plot configuration
  multi_boxplot:
    # Enable/disable multi-dataset box plot functionality
    enabled: true
    
    # Default configuration for multi-dataset comparisons
    default_settings:
      figure_size: [12, 6]
      title_format: "{metric} Distribution Comparison - Box Plots"
      xlabel: "Datasets"
      rotation: 45  # Rotation angle for x-axis labels
      grid: true
      grid_alpha: 0.3
    
    # Predefined dataset configurations
    dataset_groups:
      # Example: Compare different enhancement methods
      enhancement_comparison:
        enabled: false
        description: "Compare original vs enhanced data"
        datasets:
          - path: "path/to/original_data.xlsx"
            label: "Original"
          - path: "path/to/clahe_enhanced.xlsx"
            label: "CLAHE Enhanced"
          - path: "path/to/brightness_enhanced.xlsx"
            label: "Brightness Enhanced"
        metrics: ["pck_0.1", "pck_0.2", "pck_0.5"]
      
      # Example: Compare different detector models
      detector_comparison:
        enabled: false
        description: "Compare different pose estimation models"
        datasets:
          - path: "path/to/dwpose_results.xlsx"
            label: "DWPose"
          - path: "path/to/hrnet_results.xlsx"
            label: "HRNet"
          - path: "path/to/rtmw_results.xlsx"
            label: "RTMW"
        metrics: ["pck_0.1", "pck_0.2", "pck_0.5"]
      
      # Example: Compare different noise levels
      noise_level_comparison:
        enabled: false
        description: "Compare performance under different noise levels"
        datasets:
          - path: "path/to/clean_data.xlsx"
            label: "Clean"
          - path: "path/to/noise_20.xlsx"
            label: "20% Noise"
          - path: "path/to/noise_40.xlsx"
            label: "40% Noise"
          - path: "path/to/noise_60.xlsx"
            label: "60% Noise"
          - path: "path/to/noise_80.xlsx"
            label: "80% Noise"
        metrics: ["pck_0.1", "pck_0.2", "pck_0.5"]
    
    # Custom analysis scenarios
    custom_scenarios:
      # Users can define their own dataset comparisons here
      - name: "my_custom_comparison"
        enabled: false
        description: "Custom dataset comparison"
        datasets:
          - path: "path/to/dataset1.xlsx"
            label: "Dataset 1"
          - path: "path/to/dataset2.xlsx"
            label: "Dataset 2"
          - path: "path/to/dataset3.xlsx"
            label: "Dataset 3"
        metrics: ["pck_0.1", "pck_0.2"]
        settings:
          figure_size: [14, 8]
          title_format: "Custom {metric} Comparison"

# Usage examples:
# 1. Use default bin size: python pck_brightness_analysis.py movi
# 2. Override bin size: python pck_brightness_analysis.py movi --bin-size 10
# 3. Fine-grained analysis: python pck_brightness_analysis.py humaneva --bin-size 1 --scores 95 100
# 4. Quick overview: python pck_brightness_analysis.py movi --bin-size 20
