# MoVi Dataset Configuration
dataset:
  name: "movi"
  model: "RTMW"

paths:
  video_directory: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/MoVi/all_cropped_videos/"
  pck_file_path: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/pipeline_results/MoVi/detect_RTMW/evaluation/2025-09-11_21-43-17/2025-09-11_21-43-17_metrics.xlsx"
  save_folder: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/pipeline_results/analysis_results/MoVi/Testing"
  ground_truth_file: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/MoVi/MoVi_groundtruth/"

columns:
  subject_column: "subject"
  action_column: null
  camera_column: null
  # Define which columns to use for grouping videos
  grouping_columns: ["subject"]
  # Video naming format for display (uses Python string formatting)
  video_name_format: "{subject}_walking_cropped"

pck_scores:
  overall:
    # - "overall_overall_pck_0.25"
    # - "overall_overall_pck_0.30"
    - "overall_overall_pck_0.01"
  
  per_frame:
    # - "pck_per_frame_pck_0.25"
    # - "pck_per_frame_pck_0.30"
    - "pck_per_frame_pck_0.01"
  
  jointwise:
    - "pck_per_frame_pck_0.10"
    - "pck_per_frame_pck_0.20"
    - "pck_per_frame_pck_0.50"
  
  jointwise:
    - "LEFT_HIP_jointwise_pck_0.25"
    - "RIGHT_HIP_jointwise_pck_0.25"
    - "LEFT_KNEE_jointwise_pck_0.25"
    - "RIGHT_KNEE_jointwise_pck_0.25"
    - "LEFT_ANKLE_jointwise_pck_0.25"
    - "RIGHT_ANKLE_jointwise_pck_0.25"
    - "LEFT_HIP_jointwise_pck_0.30"
    - "RIGHT_HIP_jointwise_pck_0.30"
    - "LEFT_KNEE_jointwise_pck_0.30"
    - "RIGHT_KNEE_jointwise_pck_0.30"
    - "LEFT_ANKLE_jointwise_pck_0.30"
    - "RIGHT_ANKLE_jointwise_pck_0.30"
    - "LEFT_HIP_jointwise_pck_0.35"
    - "RIGHT_HIP_jointwise_pck_0.35"
    - "LEFT_KNEE_jointwise_pck_0.35"
    - "RIGHT_KNEE_jointwise_pck_0.35"
    - "LEFT_ANKLE_jointwise_pck_0.35"
    - "RIGHT_ANKLE_jointwise_pck_0.35"
    - "LEFT_HIP_jointwise_pck_0.40"
    - "RIGHT_HIP_jointwise_pck_0.40"
    - "LEFT_KNEE_jointwise_pck_0.40"
    - "RIGHT_KNEE_jointwise_pck_0.40"
    - "LEFT_ANKLE_jointwise_pck_0.40"
    - "RIGHT_ANKLE_jointwise_pck_0.40"

# No synchronization data for MoVi dataset
sync_data: null

# Analysis-specific configurations for MoVi
analysis:
  pck_brightness:
    # Brightness analysis configuration for MoVi
    bin_size: 2  # Default bin size for MoVi dataset
    # Dataset-specific score groups for PCK brightness analysis
    score_groups:
      all: null  # Analyze all available scores
      extremes: [0, 100]  # Extreme scores (failure and perfect)
      high_performance: [80, 85, 90, 95, 100]  # High PCK scores
      low_performance: [0, 5, 10, 15, 20]  # Low PCK scores
      mid_performance: [40, 45, 50, 55, 60]  # Mid-range performance
      movi_custom: [70, 80, 90, 95]  # MoVi-specific range
    
    # Default score group for this dataset  
    default_score_group: "extremes"
    
    # Visualization configuration for MoVi
    visualization:
      create_scatter_plots: true
      create_individual_plots: true
      create_combined_plots: true
      create_comparison_plots: true
      create_correlation_plots: true
      save_format: "svg"
      
      # MoVi-specific scatter plot settings
      scatter_plot_settings:
        figure_size: [14, 9]  # Larger plots for motion analysis
        alpha: 0.8
        marker_size: 70
        show_trend_lines: true
        show_correlation_stats: true
        colors: "plasma"  # Different colormap for MoVi
    
    # Export settings for MoVi
    export:
      csv_enabled: true
      json_enabled: true
      separate_files_per_group: true
      include_correlation_data: true
    
    # Multi-analysis configuration for MoVi
    multi_analysis:
      enabled: true
      scenarios:
        - name: "movi_motion_extremes"
          enabled: true
          score_group: "extremes"
          bin_size: 1
          description: "Detailed analysis of extreme scores for motion sequences"
          create_scatter_plots: true

  joint_brightness:
    # Joint brightness analysis configuration for MoVi
    sampling_radius: 3  # Pixel radius around joint for brightness sampling
    
    # Joints to analyze (uses COCO format joint names)
    default_joints:
      - "LEFT_HIP"
      - "RIGHT_HIP"
      - "LEFT_KNEE"
      - "RIGHT_KNEE"
      - "LEFT_ANKLE"
      - "RIGHT_ANKLE"
    
    # Additional joints that can be analyzed if available
    extended_joints:
      - "LEFT_HIP"
      - "RIGHT_HIP"
      - "LEFT_KNEE"
      - "RIGHT_KNEE"
      - "LEFT_ANKLE"
      - "RIGHT_ANKLE"
      - "LEFT_TOE"
      - "RIGHT_TOE"
    
    # Brightness analysis settings
    brightness_settings:
      frame_limit: null  # Process all frames (set to number to limit)
      normalize_brightness: false  # Whether to normalize brightness values
      brightness_threshold: null  # Optional threshold for brightness filtering
    
    # Visualization settings for joint brightness
    visualization:
      create_individual_plots: true
      create_summary_plots: true
      create_comparison_plots: true
      create_heatmaps: true
      create_per_frame_scatter: true  # New: per-frame scatter plots
      create_per_frame_lines: true    # New: per-frame line plots
      create_correlation_over_time: true  # New: correlation evolution plots
      save_format: "svg"
      
      plot_settings:
        figure_size: [15, 12]
        alpha: 0.6
        marker_size: 30
        show_correlation_stats: true
        colormap: "plasma"  # Match MoVi colormap
        line_width: 2
        scatter_size: 20
        rolling_window_size: 50  # For correlation over time analysis
    
    # Export settings
    export:
      csv_enabled: true
      include_per_frame_data: true
      include_summary_stats: true
      create_summary_report: true
          
