paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/combined_chunk0_data.csv

models:
  detector: deeplabcut

processing:
  device: cuda:0
  nms_threshold: 0.3
  detection_threshold: 0.3
  kpt_threshold: 0.3
  
noise:
  apply_poisson_noise: true
  apply_gaussian_noise: true
  apply_motion_blur: true
  apply_brightness_reduction: true
  brightness_factor: 30
  poisson_scale: 1.0
  gaussian_std: 2.0
  motion_blur_kernel_size: 5
  target_resolution: null  # or [640, 480]


filter:
  name: "gaussian"
  params:
    sigma: 0.5

  # input_dir: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/rtmw_results/rtmpose_l_whole/S1/Jog_1_(C1)/"  # <-- ADD THIS

  outlier_removal:
    enable: True
    method: "iqr"
    params:
      iqr_multiplier: 1.5

  enable_interpolation: true
  interpolation_kind: "linear"

  enable_filter_plots: true

  joints_to_filter:
    - LEFT_ANKLE
    - RIGHT_ANKLE
    - LEFT_KNEE
    - RIGHT_KNEE
    - LEFT_HIP
    - RIGHT_HIP




evaluation:
  metrics:
    - name: overall_pck
      params:
        threshold: 0.01
        joints_to_evaluate:
          - LEFT_SHOULDER
          - RIGHT_SHOULDER
          - LEFT_ELBOW
          - RIGHT_ELBOW
          - LEFT_WRIST
          - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    # - name: overall_pck
    #   params:
    #     threshold: 0.02
    #     joints_to_evaluate:
    #       - LEFT_SHOULDER
    #       - RIGHT_SHOULDER
    #       - LEFT_ELBOW
    #       - RIGHT_ELBOW
    #       - LEFT_WRIST
    #       - RIGHT_WRIST
    #       - LEFT_HIP
    #       - RIGHT_HIP
    #       - LEFT_KNEE
    #       - RIGHT_KNEE
    #       - LEFT_ANKLE
    #       - RIGHT_ANKLE

    # - name: overall_pck
    #   params:
    #     threshold: 0.05
    #     joints_to_evaluate:
    #       - LEFT_SHOULDER
    #       - RIGHT_SHOULDER
    #       - LEFT_ELBOW
    #       - RIGHT_ELBOW
    #       - LEFT_WRIST
    #       - RIGHT_WRIST
    #       - LEFT_HIP
    #       - RIGHT_HIP
    #       - LEFT_KNEE
    #       - RIGHT_KNEE
    #       - LEFT_ANKLE
    #       - RIGHT_ANKLE

    - name: jointwise_pck
      params:
        threshold: 0.01
        joints_to_evaluate:
          - LEFT_SHOULDER
          - RIGHT_SHOULDER
          - LEFT_ELBOW
          - RIGHT_ELBOW
          - LEFT_WRIST
          - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    # - name: jointwise_pck
    #   params:
    #     threshold: 0.02
    #     joints_to_evaluate:
    #       - LEFT_SHOULDER
    #       - RIGHT_SHOULDER
    #       - LEFT_ELBOW
    #       - RIGHT_ELBOW
    #       - LEFT_WRIST
    #       - RIGHT_WRIST
    #       - LEFT_HIP
    #       - RIGHT_HIP
    #       - LEFT_KNEE
    #       - RIGHT_KNEE
    #       - LEFT_ANKLE
    #       - RIGHT_ANKLE

    # - name: jointwise_pck
    #   params:
    #     threshold: 0.05
    #     joints_to_evaluate:
    #       - LEFT_SHOULDER
    #       - RIGHT_SHOULDER
    #       - LEFT_ELBOW
    #       - RIGHT_ELBOW
    #       - LEFT_WRIST
    #       - RIGHT_WRIST
    #       - LEFT_HIP
    #       - RIGHT_HIP
    #       - LEFT_KNEE
    #       - RIGHT_KNEE
    #       - LEFT_ANKLE
    #       - RIGHT_ANKLE



dataset:
 joint_enum_module: utils.joint_enum.GTJointsHumanEVa
 keypoint_format: utils.joint_enum.PredJointsDeepLabCut
 sync_data:
    data:
      S1:
        Walking 1: [667, 667, 667]
        Jog 1: [49, 50, 51]
      S2:
        Walking 1: [547, 547, 546]
        Jog 1: [493, 491, 502]
      S3:
        Walking 1: [524, 524, 524]
        Jog 1: [464, 462, 462]
