paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/S1_C1_Walking 1.csv


models:
  det_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
  det_checkpoint: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
  pose_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/projects/rtmpose/rtmpose/wholebody_2d_keypoint/rtmw-x_8xb704-270e_cocktail14-256x192.py
  pose_checkpoint: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/rtmw-x_simcc-cocktail14_pt-ucoco_270e-256x192-13a2546d_20231208.pth

processing:
  device: cuda:0
  nms_threshold: 0.5
  detection_threshold: 0.3
  kpt_threshold: 0.3

noise:
  apply_poisson_noise: true
  apply_gaussian_noise: true
  apply_motion_blur: true
  apply_brightness_reduction: true
  brightness_factor: 30
  poisson_scale: 1.0
  gaussian_std: 2.0
  motion_blur_kernel_size: 5
  target_resolution: null  # or [640, 480]


filter:
  name: "gaussian"
  params:
    sigma: 0.5

  input_dir: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/rtmw_results/rtmpose_l_whole/S1/Jog_1_(C1)/"  # <-- ADD THIS

  outlier_removal:
    enable: True
    method: "iqr"
    params:
      iqr_multiplier: 1.5

  enable_interpolation: true
  interpolation_kind: "linear"

  enable_filter_plots: true

  joints_to_filter:
    - LEFT_ANKLE
    - RIGHT_ANKLE
    - LEFT_KNEE
    - RIGHT_KNEE
    - LEFT_HIP
    - RIGHT_HIP




evaluation:
  input_dir: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/pipeline_results/HumanEva/evaluate_pose_accuracy/detect/2025-06-25_22-34-22/S1/Image_Data/Walking_1_(C1)/ # NEW FIELD
  metrics:
    - name: overall_pck
      params:
        threshold: 0.01
    # - name: jointwise_pck
    #   params:
    #     threshold: 0.05
    # - name: gat_metric
    #   params: {}


dataset:
 joint_enum_module: utils.joint_enum.GTJointsHumanEVa
 keypoint_format: utils.joint_enum.PredJointsCOCOWholebody 
 sync_data:
    data:
      S1:
        Walking 1: [667, 667, 667]
        Jog 1: [49, 50, 51]
      S2:
        Walking 1: [547, 547, 546]
        Jog 1: [493, 491, 502]
      S3:
        Walking 1: [524, 524, 524]
        Jog 1: [464, 462, 462]
