paths:
  dataset: HumanEva
  ground_truth_file: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/ground_truth/validate_combined_chunk0.csv

models:
  detector: RTMW
  det_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py
  det_checkpoint: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
  pose_config: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/configs/wholebody_2d_keypoint/rtmpose/cocktail14/rtmw-l_8xb320-270e_cocktail14-384x288.py
  pose_checkpoint: /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/models/mmpose/rtmw-dw-x-l_simcc-cocktail14_270e-384x288-20231122.pth


processing:
  device: cuda:0
  nms_threshold: 0.3
  detection_threshold: 0.3
  kpt_threshold: 0.3

# Confidence filtering for multiple skeleton detection
confidence_filtering:
  # Minimum confidence thresholds for skeleton filtering
  min_bbox_confidence: 0.3      # Minimum bounding box confidence threshold
  min_keypoint_confidence: 0.2  # Minimum keypoint confidence threshold
  
  # Weights for overall confidence score calculation (should sum to 1.0)
  bbox_weight: 0.3              # Weight for bbox confidence in overall score
  keypoint_weight: 0.7          # Weight for keypoint confidence in overall score
  
  # Minimum number of valid keypoints required for a skeleton to be considered
  min_valid_keypoints: 3        # At least 3 keypoints must be above threshold
  
  # Enable/disable confidence filtering
  enabled: true                 # Set to false to disable confidence filtering
  
noise:
  apply_poisson_noise: true
  apply_gaussian_noise: true
  apply_motion_blur: true
  apply_brightness_reduction: true
  brightness_factor: 30
  poisson_scale: 1.0
  gaussian_std: 2.0
  motion_blur_kernel_size: 5
  target_resolution: null  # or [640, 480]


filter:
  name: "gaussian"
  params:
    sigma: 0.5

  # input_dir: "/storage/Projects/Gaitly/bsehgal/lower_body_pose_est/rtmw_results/rtmpose_l_whole/S1/Jog_1_(C1)/"  # <-- ADD THIS

  outlier_removal:
    enable: True
    method: "iqr"
    params:
      iqr_multiplier: 1.5

  enable_interpolation: true
  interpolation_kind: "linear"

  enable_filter_plots: true

  joints_to_filter:
    - LEFT_ANKLE
    - RIGHT_ANKLE
    - LEFT_KNEE
    - RIGHT_KNEE
    - LEFT_HIP
    - RIGHT_HIP




evaluation:
  input_dir : /storage/Projects/Gaitly/bsehgal/lower_body_pose_est/pipeline_results/HumanEva/CLAHE_enhanced_humaneva/detect/2025-09-10_14-23-28/
  metrics:
    - name: overall_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.3
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.35
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: overall_pck
      params:
        threshold: 0.4
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.3
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.35
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: per_frame_pck
      params:
        threshold: 0.4
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: jointwise_pck
      params:
        threshold: 0.25
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: jointwise_pck
      params:
        threshold: 0.3
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE

    - name: jointwise_pck
      params:
        threshold: 0.35
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE
    - name: jointwise_pck
      params:
        threshold: 0.4
        joints_to_evaluate:
          # - LEFT_SHOULDER
          # - RIGHT_SHOULDER
          # - LEFT_ELBOW
          # - RIGHT_ELBOW
          # - LEFT_WRIST
          # - RIGHT_WRIST
          - LEFT_HIP
          - RIGHT_HIP
          - LEFT_KNEE
          - RIGHT_KNEE
          - LEFT_ANKLE
          - RIGHT_ANKLE




dataset:
 joint_enum_module: utils.joint_enum.GTJointsHumanEVa
 keypoint_format: utils.joint_enum.PredJointsDeepLabCut
 sync_data:
    data:
      S1:
        Walking 1: [667, 667, 667]
        Jog 1: [49, 50, 51]
        Box 1: [36, 45, 56]
        Gestures 1: [32,22,20]
      S2:
        Walking 1: [547, 547, 546]
        Jog 1: [493, 491, 502]
        Box 1: [120, 111,117]
      S3:
        Walking 1: [524, 524, 524]
        Jog 1: [464, 462, 462]
        Box 1: [20,22,22]
        Gestures 1: [1,1,1]
